// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6otBej6WC3ImKaArQG0eRnXdRyaqm63U',
    appId: '1:610091935718:web:5fff3c4e092a091ec69827',
    messagingSenderId: '610091935718',
    projectId: 'practice-real-demo',
    authDomain: 'practice-real-demo.firebaseapp.com',
    databaseURL: 'https://practice-real-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practice-real-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvC9cQ6VGw4IgDEv48nX4kgZSlwgIN9U',
    appId: '1:610091935718:android:fe07474f1179aaafc69827',
    messagingSenderId: '610091935718',
    projectId: 'practice-real-demo',
    databaseURL: 'https://practice-real-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'practice-real-demo.appspot.com',
  );
}
